# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the bin/rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
# Movie.create(title:"ANT-MAN AND THE WASP: QUANTUMANIA", genre:"Action/Adventure", director:"Peyton Reed", rating:"PG-13", runtime:"2 hr 5 min", description:"Super Heroes Scott Lang (Paul Rudd) and Hope Van Dyne (Evangeline Lilly) return to continue their adventures as Ant-Man and The Wasp. Together, with Hope’s parents Janet Van Dyne (Michelle Pfeiffer) and Hank Pym (Michael Douglas), and Scott’s daughter Cassie Lang (Kathryn Newton), the family finds themselves exploring the Quantum Realm, interacting with strange new creatures and embarking on an adventure that will push them beyond the limits of what they thought possible.", image:"https://images.fandango.com/ImageRenderer/200/0/redesign/static/img/default_poster.png/0/images/masterrepository/Fandango/228957/DB_Payoff_1-Sht_v5a_sm.jpg")
Movie.create(title:"PUSS IN BOOTS: THE LAST WISH ", genre:"Action/Adventure", director:"Joel Crawford", rating:"PG", runtime:"1 hr 42 min", description:"Puss in Boots discovers that his passion for peril and disregard for safety have taken their toll. Puss has burned through eight of his nine lives, though he lost count along the way. Getting those lives back will send Puss in Boots on his grandest quest yet.", image:"https://images.fandango.com/ImageRenderer/200/0/redesign/static/img/default_poster.png/0/images/masterrepository/Fandango/227301/PIB_Adv1Sheet3_GoodEvil_RGB_1.jpg")
Movie.create(title:"COCAINE BEAR", genre:"Suspense/Thriller", director:"Elizabeth Banks", rating:"R", runtime:"1 hr 35 min", description:"Inspired by the 1985 true story of a drug runner's plane crash, missing cocaine, and the black bear that ate it, this wild thriller finds an oddball group of cops, criminals, tourists and teens converging in a Georgia forest where a 500- pound apex predator has ingested a staggering amount of cocaine and gone on a coke-fueled rampage for more blow … and blood.", image:"https://images.fandango.com/ImageRenderer/200/0/redesign/static/img/default_poster.png/0/images/masterrepository/Fandango/230407/CCB_Tsr12_1080x1920pxH_RGB_2_cr.jpg")
Movie.create(title:"SHAZAM! FURY OF THE GODS", genre:"Action/Adventure", director:"David F. Sandberg", rating:"PG-13", runtime:"2 hr 10 min", description:"From New Line Cinema comes “Shazam! Fury of the Gods,” which continues the story of teenage Billy Batson who, upon reciting the magic word “SHAZAM!,” is transformed into his adult Super Hero alter ego, Shazam.", image:"https://images.fandango.com/ImageRenderer/200/0/redesign/static/img/default_poster.png/0/images/masterrepository/Fandango/227897/FND_poster_ShazamFuryOfTheGods-Presale.jpg")
#   Character.create(name: "Luke", movie: movies.first)

